CREATE TABLE TB_CLIENTES_SISTEMA
(
    ID_CLIENTE NUMBER PRIMARY KEY,
    CPF VARCHAR2(11),
    NOME VARCHAR2(100),
    ENDERECO VARCHAR2(150),
    EMAIL VARCHAR2(50),
    DATA_CADASTRO DATE,
    TELEFONE VARCHAR2(20)
);


CREATE TABLE TB_STATUS_PEDIDO
(
    ID_STATUS NUMBER PRIMARY KEY,
    NOME VARCHAR2(20),
    DESCRICAO VARCHAR2(50),
    ORDEM NUMBER
);


CREATE TABLE TB_FORNECEDOR
(
    ID_FORNECEDOR NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    CNPJ VARCHAR2(14),
    EMAIL VARCHAR2(100),
    TELEFONE VARCHAR2(20),
    ATIVO NUMBER(1)
);


CREATE TABLE TB_PRODUTO_SISTEMA
(
    ID_PRODUTO NUMBER PRIMARY KEY,
    ID_FORNECEDOR NUMBER,
    NOME VARCHAR2(50),
    DESCRICAO VARCHAR2(100),
    TIPO VARCHAR2(20),
    QTDE_ESTOQUE NUMBER(10,2),
    ATIVO NUMBER(1),
    DATA_CADASTRO DATE,

    CONSTRAINT FK_PRODUTO_FORNECEDOR
        FOREIGN KEY (ID_FORNECEDOR)
        REFERENCES TB_FORNECEDOR(ID_FORNECEDOR)
);


CREATE TABLE TB_ENDERECO
(
    ID_ENDERECO NUMBER PRIMARY KEY,
    ID_CLIENTE NUMBER,
    LOGRADOURO VARCHAR2(50),
    NUMERO VARCHAR2(20),
    BAIRRO VARCHAR2(20),
    CIDADE VARCHAR2(20),
    ESTADO VARCHAR2(20),
    CEP VARCHAR2(20),
    COMPLEMENTO VARCHAR2(30),
    ATIVO NUMBER(1),

    CONSTRAINT FK_ENDERECO_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES TB_CLIENTES_SISTEMA(ID_CLIENTE)
);


CREATE TABLE TB_PEDIDO_SISTEMA
(
    ID_PEDIDO NUMBER PRIMARY KEY,
    ID_CLIENTE NUMBER,
    ID_STATUS NUMBER,
    DATA_PEDIDO DATE,
    DATA_PREVISTA DATE,
    OBSERVACAO VARCHAR2(100),
    VALOR_TOTAL NUMBER(10,2),

    CONSTRAINT FK_PEDIDO_SISTEMA_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
        REFERENCES TB_CLIENTES_SISTEMA(ID_CLIENTE),

    CONSTRAINT FK_PEDIDO_SISTEMA_STATUS
        FOREIGN KEY (ID_STATUS)
        REFERENCES TB_STATUS_PEDIDO(ID_STATUS)
);


CREATE TABLE TB_ESTOQUE
(
    ID_ESTOQUE NUMBER PRIMARY KEY,
    ID_PRODUTO NUMBER,
    QUANTIDADE NUMBER(10,2),
    DATA_CADASTRO DATE,

    CONSTRAINT FK_ESTOQUE_PRODUTO
        FOREIGN KEY (ID_PRODUTO)
        REFERENCES TB_PRODUTO_SISTEMA(ID_PRODUTO)
);


CREATE TABLE TB_PEDIDO_PRODUTO
(
    ID_PEDIDO_PRODUTO NUMBER PRIMARY KEY,
    ID_PEDIDO NUMBER,
    ID_PRODUTO NUMBER,
    QUANTIDADE NUMBER(10,2),
    PRECO_UNITARIO NUMBER(10,2),
    DESCONTO NUMBER(10,2),
    SUBTOTAL NUMBER(10,2),

    CONSTRAINT FK_PEDIDO_PRODUTO_PEDIDO
        FOREIGN KEY (ID_PEDIDO)
        REFERENCES TB_PEDIDO_SISTEMA(ID_PEDIDO),

    CONSTRAINT FK_PEDIDO_PRODUTO_PRODUTO
        FOREIGN KEY (ID_PRODUTO)
        REFERENCES TB_PRODUTO_SISTEMA(ID_PRODUTO)
);


CREATE TABLE TB_PRODUTO_RESERVADO
(
    ID_RESERVA NUMBER PRIMARY KEY,
    ID_PRODUTO NUMBER,
    ID_PEDIDO NUMBER,
    QUANTIDADE NUMBER(10,2),
    DATA_RESERVA DATE,
    ATIVO NUMBER(1),

    CONSTRAINT FK_RESERVA_PRODUTO
        FOREIGN KEY (ID_PRODUTO)
        REFERENCES TB_PRODUTO_SISTEMA(ID_PRODUTO),

    CONSTRAINT FK_RESERVA_PEDIDO
        FOREIGN KEY (ID_PEDIDO)
        REFERENCES TB_PEDIDO_SISTEMA(ID_PEDIDO)
);


CREATE TABLE TB_PEDIDO_COMENTARIO
(
    ID_COMENTARIO NUMBER PRIMARY KEY,
    ID_PEDIDO NUMBER,
    USUARIO VARCHAR2(20),
    COMENTARIO VARCHAR2(200),
    DATA_COMENTARIO DATE,

    CONSTRAINT FK_COMENTARIO_PEDIDO
        FOREIGN KEY (ID_PEDIDO)
        REFERENCES TB_PEDIDO_SISTEMA(ID_PEDIDO)
);


CREATE TABLE TB_STATUS_PEDIDO_HISTORICO
(
    ID_HISTORICO NUMBER PRIMARY KEY,
    ID_PEDIDO NUMBER,
    ID_STATUS NUMBER,
    DATA_ALTERACAO DATE,
    USUARIO VARCHAR2(20),
    OBSERVACAO VARCHAR2(50),

    CONSTRAINT FK_HISTORICO_PEDIDO
        FOREIGN KEY (ID_PEDIDO)
        REFERENCES TB_PEDIDO_SISTEMA(ID_PEDIDO),

    CONSTRAINT FK_HISTORICO_STATUS
        FOREIGN KEY (ID_STATUS)
        REFERENCES TB_STATUS_PEDIDO(ID_STATUS)
);


CREATE TABLE PAGAMENTO
(
    ID_PAGAMENTO NUMBER PRIMARY KEY,
    ID_PEDIDO NUMBER,
    TIPO_PAGAMENTO VARCHAR2(30),
    BOLETO_URL VARCHAR2(255),
    DATA_PAGAMENTO DATE,
    VALOR NUMBER(10,2),
    STATUS_PAGAMENTO VARCHAR2(30),
    OBSERVACAO VARCHAR2(200),

    CONSTRAINT FK_PAGAMENTO_PEDIDO
        FOREIGN KEY (ID_PEDIDO)
        REFERENCES TB_PEDIDO_SISTEMA(ID_PEDIDO)
);