CREATE SEQUENCE TB_CLIENTES_SISTEMA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TB_PRODUTO_SISTEMA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TB_FORNECEDOR_SEQ START WITH 1 INCREMENT BY 1;
